<?php
namespace Tests\AMQPy\Serializers;

use \PHPUnit_Framework_TestCase;

use \AMQPy\Serializers\PlainText;


/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-03 at 00:21:46.
 */
class PlainTextTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var PlainText
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PlainText;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers PlainText::serialize
     * @todo   Implement testSerialize().
     */
    public function testSerialize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PlainText::parse
     * @todo   Implement testParse().
     */
    public function testParse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AMQPy\Serializers\PlainText::getContentType
     * @todo   Implement testGetContentType().
     */
    public function testGetContentType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
